### ISSUE TITLE
Add some images to each section

### ISSUE THREAD

**Issue by iamyogik** [iamyogik/onboarding#1]
Add some images to each section on the onboarding. The old ones have been deleted from the web. Create a new folder named assets/images and put all the images locally there.

**Comment by gabriel-arauj** [comment]
What images should i put?

**Comment by HenrySabio** [comment]
@iamyogik I think we need to know what type of image that should be added.
Nature? People? People in offices? Animals? Etc.

Need more details to be able to add images that are relevant to the websites purpose.

**Comment by iamyogik** [comment]
You can add images that are relevant to each section. Like for mobile no. you can add a illustration showing some one adding his/her mobile no. Be creative and see what looks great on each section.

**Comment by LarisaArmstrong** [comment]
I am going to add some illustrations
