### ISSUE TITLE
Page resize issue on section change

### ISSUE THREAD

**Issue by iamyogik** [iamyogik/onboarding#2]
The page resizes and a scroll bar appears for a few milliseconds when each section is changed. Try removing that.

**Comment by beatrizsmerino** [comment]
I want colaborate in this ;)

**Comment by iamyogik** [comment]
Great. Go ahead with it.

**Comment by beatrizsmerino** [comment]
It's done.

I created a branch with my name (**beatrizsmerino**) with 2 commits:
- [Removed the scroll bar when the page resize](https://github.com/iamyogik/onboarding/pull/5)
- [Add some images to each section](https://github.com/iamyogik/onboarding/pull/4)
